INSERT INTO Genres (`genre_url`, `genre_title`, `genre_father`) VALUES
('ciencia-ficcion-y-fantasia', 'Ciencia ficción y fantasía', NULL),
	('historia-alternativa', 'Historia alternativa', 'ciencia-ficcion-y-fantasia'),
	('epica', 'Épica', 'ciencia-ficcion-y-fantasia'),
	('heroica', 'Heróica', 'ciencia-ficcion-y-fantasia'),
	('cyberpunk', 'Cyberpunk', 'ciencia-ficcion-y-fantasia'),
	('espacio', 'Espacio', 'ciencia-ficcion-y-fantasia'),
	('horror-y-mistica', 'Horror y mística', 'ciencia-ficcion-y-fantasia'),
	('fantasia', 'Fantasía', 'ciencia-ficcion-y-fantasia'),
	('ciencia-ficcion', 'Ciencia Ficción', 'ciencia-ficcion-y-fantasia'),

('literatura-policiaca', 'Literatura policiaca', NULL),
	('espionaje', 'Espionaje', 'literatura-policiaca'),
	('detectives', 'Detectives', 'literatura-policiaca'),

('prosa', 'Prosa', NULL),
    ('clasicos-en-prosa', 'Clásicos en prosa', 'prosa'),
    ('prosa-historica', 'Prosa histórica', 'prosa'),
    ('prosa-contemporanea', 'Prosa contemporánea', 'prosa'),
    ('contracultura', 'Contracultura', 'prosa'),

('literatura-romantica', 'Literatura romática', NULL),
    ('romance-contemporaneo', 'Romance contemporáneo', 'literatura-romantica'),
    ('romance-historico', 'Romance histórico', 'literatura-romantica'),
    ('erotica', 'Erótica', 'literatura-romantica'),

('aventuras', 'Aventuras', NULL),
	('accion', 'Acción', 'aventuras'),
    ('indios-y-vaqueros', 'Indios y vaqueros', 'aventuras'),

('literatura-infantil', 'Literatura infantil', NULL),
    ('cuentos-de-hadas', 'Cuentos de hadas', 'literatura-infantil'),

('poesia-y-dramaturgia', 'Poesía y Dramaturgia', NULL),
    ('poesia', 'Poesía', 'poesia-y-dramaturgia'),
    ('dramaturgia', 'Dramaturgia', 'poesia-y-dramaturgia'),

('literatura-antigua', 'Literatura antigua', NULL),
    ('literatura-europea', 'Literatura europea', 'literatura-antigua'),
	('literatura-medieval', 'Literatura medieval', 'literatura-antigua'),
    ('antiguo-oriente', 'Antiguo Oriente', 'literatura-antigua'),
    ('mitos-leyendas-y-epopeyas', 'Mitos, leyendas y epopeyas', 'literatura-antigua'),

('cientifico-educativo', 'Científico-educativo', NULL),
    ('historia', 'Historia', 'cientifico-educativo'),
    ('psicologia', 'Psicología', 'cientifico-educativo'),
    ('sociologia', 'Sociología', 'cientifico-educativo'),
    ('teologia', 'Teología', 'cientifico-educativo'),
    ('filosofia', 'Filosofía', 'cientifico-educativo'),
    ('politica', 'Política', 'cientifico-educativo'),
    ('negocios', 'Negocios', 'cientifico-educativo'),
    ('derecho', 'Derecho', 'cientifico-educativo'),
    ('linguistica', 'Lingüística', 'cientifico-educativo'),
    ('medicina', 'Medicina', 'cientifico-educativo'),
    ('fisica', 'Física', 'cientifico-educativo'),
    ('matematicas', 'Matemáticas', 'cientifico-educativo'),
	('quimica', 'Química', 'cientifico-educativo'),
    ('biologia', 'Biología', 'cientifico-educativo'),
    ('tecnica', 'Técnica', 'cientifico-educativo'),

('computadoras-e-internet', 'Computadoras e Internet', NULL),
    ('internet', 'Internet', 'computadoras-e-internet'),
    ('programacion', 'Programación', 'computadoras-e-internet'),
    ('harware', 'Hardware', 'computadoras-e-internet'),
    ('software', 'Software', 'computadoras-e-internet'),
    ('bases-de-datos', 'Bases de datos', 'computadoras-e-internet'),
    ('sistemas-operativos', 'Sistemas operativos', 'computadoras-e-internet'),
	('redes', 'Redes', 'computadoras-e-internet'),

('obras-de-referencia', 'Obras de referencia', NULL),
    ('enciclopedias', 'Enciclopedias', 'obras-de-referencia'),
    ('diccionarios', 'Diccionarios', 'obras-de-referencia'),
    ('guias-de-viaje', 'Guías de viaje', 'obras-de-referencia'),

('no-ficcion', 'No ficción', NULL),
    ('biografias-y-memorias', 'Biografías y memorias', 'no-ficcion'),
    ('publicismo', 'Publicismo', 'no-ficcion'),
    ('critica', 'Crítica', 'no-ficcion'),
    ('arte-y-diseno', 'Arte y diseño', 'no-ficcion'),

('religion-y-autoayuda', 'Religión y autoauyuda', NULL),
    ('religion', 'Religión', 'religion-y-autoayuda'),
    ('esoterismo', 'Esoterismo', 'religion-y-autoayuda'),
    ('superacion-personal', 'Superación personal', 'religion-y-autoayuda'),

('humor','Humor', NULL),
    ('chistes', 'Chistes', 'humor'),

('hogar-y-familia', 'Hogar y familia', NULL),
    ('cocina', 'Cocina', 'hogar-y-familia'),
    ('mascotas', 'Mascotas', 'hogar-y-familia'),
    ('aficiones-y-manualidades', 'Aficiones y manualidades', 'hogar-y-familia'),
    ('entretenimiento', 'Entretenimiento', 'hogar-y-familia'),
    ('salud', 'Salud', 'hogar-y-familia'),
    ('jardineria', 'Jardinería', 'hogar-y-familia'),
    ('deportes', 'Deportes', 'hogar-y-familia')